### PR TITLE
redux integration, load photos from server

### PR DESCRIPTION
**Pull request by amitnjha**
Cleanup pending.
eslint has been setup but there are 41 error that need to be resolved.

Run eslint as -
npx eslint src.

### CODE REVIEW

**Comment by amitnjha** [comment]
@ankit373 Can you review this and maybe merge? I would like this to be updated on website if possible.

**Comment by ankit373** [comment]
Gone through this, unable to build on native

**Comment by amitnjha** [comment]
> Unable to build on native but all seems good, not sure about the errors

You will have to to npm install perhaps before yarn start.
What is the error you are getting?

**Comment by ankit373** [comment]
The error after npm install is listed:

npm ERR! code EJSONPARSE
npm ERR! file C:\Users\USER\aditijha.org\aditijha.org\package.json
npm ERR! Merge conflict detected in your package.json.
npm ERR! npm ERR! Please resolve the package.json conflict and retry the command:
npm ERR! npm ERR! $ C:\Program Files\nodejs\node.exe C:\ProgramFiles\nodejs\node_modules\npm\bin\npm-cli.js install
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Roaming\npm-cache\_logs\2020-05-21T00_32_06_732Z-debug.log

**Comment by amitnjha** [comment]
> The error after npm install is listed:
> 
> npm ERR! code EJSONPARSE
> npm ERR! file C:\Users\USER\aditijha.org\aditijha.org\package.json
> npm ERR! Merge conflict detected in your package.json.
> npm ERR! npm ERR! Please resolve the package.json conflict and retry the command:
> npm ERR! npm ERR! $ C:\Program Files\nodejs\node.exe C:\ProgramFiles\nodejs\node_modules\npm\bin\npm-cli.js install
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\USER\AppData\Roaming\npm-cache_logs\2020-05-21T00_32_06_732Z-debug.log

I think it's happening because of the fork you are in. May be delete everything and checkout this project/branch and then it will work. This of course assumes you don't have anything pending on the slave branch.

**Comment by ankit373** [comment]
> > The error after npm install is listed:
> > npm ERR! code EJSONPARSE
> > npm ERR! file C:\Users\USER\aditijha.org\aditijha.org\package.json
> > npm ERR! Merge conflict detected in your package.json.
> > npm ERR! npm ERR! Please resolve the package.json conflict and retry the command:
> > npm ERR! npm ERR! $ C:\Program Files\nodejs\node.exe C:\ProgramFiles\nodejs\node_modules\npm\bin\npm-cli.js install
> > npm ERR! A complete log of this run can be found in:
> > npm ERR! C:\Users\USER\AppData\Roaming\npm-cache_logs\2020-05-21T00_32_06_732Z-debug.log
> 
> I think it's happening because of the fork you are in. May be delete everything and checkout this project/branch and then it will work. This of course assumes you don't have anything pending on the slave branch.

Yes Definitely will go  with that.

**Comment by ankit373** [comment]
MainContainer doesn't add any additional component to the current.

**Pull request merged**
